name: butler

on:
  issue_comment:
    types: [created]  # Trigger the workflow when a new comment is created on an issue or PR

permissions:
  pull-requests: write

jobs:
    chat:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run Code Butler
              uses: ca-dp/code-butler@v1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                cmd: chat
                comment_body: ${{ github.event.comment.body }}