name: butler

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'comment ${{ github.event.comment.body }}'
      - run: echo '${{ toJson(github.event) }}'

  chat:
    if: contains(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Butler Chat
        uses: ca-dp/code-butler
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          cmd: chat
          comment_body: ${{ github.event.comment.body }}

  review:
    if: contains(github.event.comment.body, '/review')
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Butler Review
        uses: ca-dp/code-butler
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          cmd: review
