name: thanks

on:
  issues:
    types: opened  # Trigger the workflow when a new issue is opened
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  thanks:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    permissions:
      issues: write  # Grant write access to issues
    steps:
      - uses: actions/github-script@v7  # Use the GitHub Script Action to run JavaScript code
        id: issue_script
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Pass the GitHub token for authentication
          script: |
            const issue_number = context.issue.number || 2;  // Get the issue number; fallback to 2 if unavailable
            console.log(`issue_number: ${issue_number}`);

            const owner = context.repo.owner;  // Get the repository owner
            const repo = context.repo.repo;    // Get the repository name

            // Retrieve information about the issue
            const issue = await github.rest.issues.get({
              repo, owner, issue_number
            });
            console.log(`issue: ${issue}`);

            // Create a comment thanking the contributor
            const comment = await github.rest.issues.createComment({
              repo, owner, issue_number,
              body: "Thanks for your contribution!"
            });
            console.log(`comment id: ${comment.data.id}`);
            console.log(comment.data);

            // Add a label to the issue for later review
            github.rest.issues.addLabels({
              repo, owner, issue_number,
              labels: ['todo-review']
            });

            // Make the comment ID available to subsequent steps
            return comment.data.id;

      - run: echo 'comment id=${{ steps.issue_script.outputs.result }}'  # Print the comment ID for debugging purposes
