name: upper-build

on:
    push:
        paths:
        - ".github/workflows/upper-build.yml"
        - "upper/**"
    workflow_dispatch: # manually

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - run: go version
            - uses: actions/setup-go@v5
              with:
                go-version-file: ./upper/go.mod
                cache-dependeency-path: ./upper/go.sum
            - run: go mod download
              working-directory: upper
            - run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: upper

        